<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <title>Welcome to Rick&#39;s Page  | 异常</title>
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">

    <meta name="viewport" content="width=device-width,minimum-scale=1">
    <meta name="generator" content="Hugo 0.52" />
    
    
      <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
    

    
    
      <link href="/rick/dist/css/app.955516233bcafa4d2a1c13cea63c7b50.css" rel="stylesheet">
    

    

    
      
    

    

    <meta property="og:title" content="异常" />
<meta property="og:description" content="异常 一、try、catch、throw 可以使用 throw 语句在代码块中的任何地方抛出异常。throw 语句的操作数可以是任意的表达式，表达式的结果的类型决定了抛出的异常的类型
int main( ) { try{ throw &quot;exception&quot;; }catch(const char * e){ cout &lt;&lt; e &lt;&lt; endl; }catch(...){ // 捕获所有异常 cout &lt;&lt; &quot;...&quot; &lt;&lt; endl; } { cout &lt;&lt; &quot;finally&quot; &lt;&lt; endl; } return 0; }  Start exception finally 0 Finish  二、std::exception class exception { public: exception() throw(); exception(const exception&amp; rhs) throw(); exception&amp; operator=(const exception&amp; rhs) throw(); virtual ~exception() throw(); virtual const char *what() const throw(); };  派生了两个异常类：" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://874656645.github.io/rick/posts/57-%E5%BC%82%E5%B8%B8/" /><meta property="article:published_time" content="2021-12-30T15:34:27&#43;08:00"/>
<meta property="article:modified_time" content="2021-12-30T15:34:27&#43;08:00"/>

<meta itemprop="name" content="异常">
<meta itemprop="description" content="异常 一、try、catch、throw 可以使用 throw 语句在代码块中的任何地方抛出异常。throw 语句的操作数可以是任意的表达式，表达式的结果的类型决定了抛出的异常的类型
int main( ) { try{ throw &quot;exception&quot;; }catch(const char * e){ cout &lt;&lt; e &lt;&lt; endl; }catch(...){ // 捕获所有异常 cout &lt;&lt; &quot;...&quot; &lt;&lt; endl; } { cout &lt;&lt; &quot;finally&quot; &lt;&lt; endl; } return 0; }  Start exception finally 0 Finish  二、std::exception class exception { public: exception() throw(); exception(const exception&amp; rhs) throw(); exception&amp; operator=(const exception&amp; rhs) throw(); virtual ~exception() throw(); virtual const char *what() const throw(); };  派生了两个异常类：">


<meta itemprop="datePublished" content="2021-12-30T15:34:27&#43;08:00" />
<meta itemprop="dateModified" content="2021-12-30T15:34:27&#43;08:00" />
<meta itemprop="wordCount" content="183">



<meta itemprop="keywords" content="" />
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="异常"/>
<meta name="twitter:description" content="异常 一、try、catch、throw 可以使用 throw 语句在代码块中的任何地方抛出异常。throw 语句的操作数可以是任意的表达式，表达式的结果的类型决定了抛出的异常的类型
int main( ) { try{ throw &quot;exception&quot;; }catch(const char * e){ cout &lt;&lt; e &lt;&lt; endl; }catch(...){ // 捕获所有异常 cout &lt;&lt; &quot;...&quot; &lt;&lt; endl; } { cout &lt;&lt; &quot;finally&quot; &lt;&lt; endl; } return 0; }  Start exception finally 0 Finish  二、std::exception class exception { public: exception() throw(); exception(const exception&amp; rhs) throw(); exception&amp; operator=(const exception&amp; rhs) throw(); virtual ~exception() throw(); virtual const char *what() const throw(); };  派生了两个异常类："/>

  </head>

  <body class="ma0 avenir bg-near-white">

    
   
  

  <header>
    <div class="bg-black">
      <nav class="pv3 ph3 ph4-ns" role="navigation">
  <div class="flex-l justify-between items-center center">
    <a href="https://874656645.github.io/rick/" class="f3 fw2 hover-white no-underline white-90 dib">
      Welcome to Rick&#39;s Page
    </a>
    <div class="flex-l items-center">
      
      
<div hidden>
  <span id="new-window-0">Opens in a new window</span>
  <span id="new-window-1">Opens an external site</span>
  <span id="new-window-2">Opens an external site in a new window</span>
</div>









    </div>
  </div>
</nav>

    </div>
  </header>



    <main class="pb7" role="main">
      
  
  <article class="flex-l flex-wrap justify-between mw8 center ph3 ph0-l">

    <header class="mt4 w-100">
      <p class="f6 b helvetica tracked">
          
        POSTS
      </p>
      <h1 class="f1 athelas mb1">异常</h1>
      
      <time class="f6 mv4 dib tracked" datetime="2021-12-30T15:34:27&#43;08:00">December 30, 2021</time>      
      
      
    </header>

    <main class="nested-copy-line-height lh-copy serif f4 nested-links nested-img mid-gray pr4-l w-two-thirds-l">

<h2 id="异常">异常</h2>

<h3 id="一-try-catch-throw">一、try、catch、throw</h3>

<p>可以使用 throw 语句在代码块中的任何地方抛出异常。<strong>throw 语句的操作数可以是任意的表达式</strong>，表达式的结果的类型决定了抛出的异常的类型</p>

<pre><code class="language-C++">int main( )
{  
    try{
        throw &quot;exception&quot;;
    }catch(const char * e){
        cout &lt;&lt; e &lt;&lt; endl;
    }catch(...){    // 捕获所有异常
        cout &lt;&lt; &quot;...&quot; &lt;&lt; endl;
    }
    {
        cout &lt;&lt; &quot;finally&quot; &lt;&lt; endl;
    }
    
    return 0;
}
</code></pre>

<pre><code class="language-text">Start
exception
finally
0
Finish
</code></pre>

<h3 id="二-std-exception">二、std::exception</h3>

<pre><code class="language-C++">class exception {
public:
   exception() throw();
   exception(const exception&amp; rhs) throw();
   exception&amp; operator=(const exception&amp; rhs) throw();
   virtual ~exception() throw();
   virtual const char *what() const throw();
};
</code></pre>

<p><strong>派生了两个异常类：</strong></p>

<table>
<thead>
<tr>
<th align="left">类名</th>
<th align="left">描述</th>
</tr>
</thead>

<tbody>
<tr>
<td align="left">logic_erro</td>
<td align="left">报告程序的逻辑错误，<strong>可在程序执行前被检测到</strong></td>
</tr>

<tr>
<td align="left">runtime_erro</td>
<td align="left">报告程序运行时的错误，只有在运行的时候才能检测到</td>
</tr>
</tbody>
</table>

<p><strong>由logic_erro派生的异常类：</strong></p>

<table>
<thead>
<tr>
<th align="left">类名</th>
<th align="left">描述</th>
</tr>
</thead>

<tbody>
<tr>
<td align="left">domain_error</td>
<td align="left">报告违反了前置条件</td>
</tr>

<tr>
<td align="left">invalid_argument</td>
<td align="left">指出函数的一个无效参数</td>
</tr>

<tr>
<td align="left">length_error</td>
<td align="left">指出有一个产生超过NPOS长度的对象的企图（NPOS为size_t的最大可表现值</td>
</tr>

<tr>
<td align="left">out_of_range</td>
<td align="left">报告参数越界</td>
</tr>

<tr>
<td align="left">bad_cast</td>
<td align="left">在运行时类型识别中有一个无效的dynamic_cast表达式</td>
</tr>

<tr>
<td align="left">bad_typeid</td>
<td align="left">报告在表达式typeid(*p)中有一个空指针P</td>
</tr>
</tbody>
</table>

<p><strong>由runtime_error派生的异常：</strong></p>

<table>
<thead>
<tr>
<th align="left">类名</th>
<th align="left">描述</th>
</tr>
</thead>

<tbody>
<tr>
<td align="left">range_error</td>
<td align="left">报告违反了后置条件</td>
</tr>

<tr>
<td align="left">overflow_error</td>
<td align="left">报告一个算术溢出</td>
</tr>

<tr>
<td align="left">bad_alloc</td>
<td align="left">报告一个存储分配错误</td>
</tr>
</tbody>
</table>

<p><img src="../img/exception.png" alt="std::exception" /></p>

<h3 id="三-自定义异常">三、自定义异常</h3>

<p>可以通过继承和重载 exception 类来定义新的异常</p>

<pre><code class="language-C++">struct MyException : public exception
{
  const char * what () const throw ()   // 表明没有任何异常抛出
  {
    return &quot;C++ Exception&quot;;
  }
};
 
int main()
{
    try
    {
        throw MyException();
    }
    catch(MyException&amp; e)
    {
        cout &lt;&lt; &quot;MyException caught&quot; &lt;&lt; endl;
        cout &lt;&lt; e.what() &lt;&lt; endl;
    }
    catch(std::exception&amp; e)
    {
        //其他的错误
    }
    catch(...)
    {
        cout &lt;&lt; &quot;...&quot; &lt;&lt; endl;
    }
    {
        cout &lt;&lt; &quot;finally&quot; &lt;&lt; endl;
    }
    return 0;
}
</code></pre>

<pre><code class="language-text">Start
MyException caught
C++ Exception
finally
0
Finish
</code></pre>
<ul class="pa0">
  
</ul>
<div class="mt6">
        
      </div>
    </main>

    <aside class="w-30-l mt6-l">




</aside>

  </article>

    </main>
    <footer class="bg-black bottom-0 w-100 pa3" role="contentinfo">
  <div class="flex justify-between">
  <a class="f4 fw4 hover-white no-underline white-70 dn dib-ns pv2 ph3" href="https://874656645.github.io/rick/" >
    &copy; 2021 Welcome to Rick&#39;s Page
  </a>
    <div>
<div hidden>
  <span id="new-window-0">Opens in a new window</span>
  <span id="new-window-1">Opens an external site</span>
  <span id="new-window-2">Opens an external site in a new window</span>
</div>








</div>
  </div>
</footer>

    

  <script src="/rick/dist/js/app.3fc0f988d21662902933.js"></script>


  </body>
</html>
